use unox;

SELECT * FROM Screen;
SELECT * FROM Movie;
SELECT * FROM Seat;
SELECT * FROM MovieCast;
SELECT * FROM Review;
SELECT * FROM Showw;
SELECT * FROM User;
SELECT * FROM Membership;
SELECT * FROM ShowSeat;
SELECT * FROM Booking;
SELECT * FROM PaymentGateway;
SELECT * FROM Payment;
SELECT * FROM Ticket;
SELECT * FROM FoodItem;
SELECT * FROM FoodItemSize;
SELECT * FROM FoodOrder;
SELECT * FROM FoodOrderItem;
SELECT * FROM PointsTransaction;